### ISSUE TITLE
Comment Text Color

### ISSUE THREAD

**Issue by stolencard** [nicu03/dark-youtube-theme#11]
The comments section text is black and is very hard to read.

**Comment by nicu03** [comment]
@stolencard can you please provide more details like:
browser version, OS, some screenshots ?
Thanks!

**Comment by stolencard** [comment]
I'm assuming since my text color has been fixed it has been resolved, Or do you still want me to provide screenshots?

**Comment by nicu03** [comment]
@stolencard  i didn't fix anything, some users are still complaining about this issue, but i still cannot reproduce it :(
your Os and browser version might still help
thanks

**Comment by kritzseb** [comment]
Hey,

I have the same problem, that the comment text color is black.
My browser is Chrome and my OS is Windows 8.1 Pro, 64-Bit

In the styles there is no explicit command for the css to make the text white/grey/whatever. (Maybe that helps you to find the bug?)

Greetings

**Comment by nicu03** [comment]
hi there!
thanks a lot, i just submitted a new version, 2.1, with some fixes
if it's still not working, i'll have to digg deeper
thanks again !

**Comment by kritzseb** [comment]
Hey, thanks for the fast respond.
Unfortunately it is still the same.
I added a screenshot in the mail.

Would you like a screenshot from a specific code snap? Because you can't
reproduce the bug, so I think maybe this will help you.

Greetings.

2016-01-29 12:52 GMT+01:00 Nicu Natrapeiu <notifications@github.com>:

> hi there!
> thanks a lot, i just submitted a new version, 2.1, with some fixes
> if it's still not working, i'll have to digg deeper
> thanks again !

**Comment by stolencard** [comment]
It was only fixed on one yt video then went back to normal, I'm using Chrome and Windows 10.

**Comment by mchladek** [comment]
I'm having the same issue with Firefox 44 on Arch Linux. Let me know if any more info would be helpful. Thanks for looking into it!

**Comment by Sephyr** [comment]
Hi there,

I ran into the same issue with the comments being black.
After checking the CSS it seems that there's no injection taking place whatsoever resulting in the text reverting to default (body) black.
I noted that you had defined .comment-text-content with #8d8d8d (subtle grey) but not .comment-renderer-text-content which holds the comments text. It seems the classname mightve changed and is causing this?

I tried adding the class in the dark.css under User Data\Default\Extensions\<letters>\2.1_0\dark.css, but this didnt seem to get picked up (possibly due to inexperience on my part with extensions :P ).

Hope this helps.

Running Version 48.0.2564.97 m on Windows 10

**Comment by bauerp** [comment]
Same issue in Safari (El Capitan)

**Comment by nicu03** [comment]
Thanks everyone for the help, i can't reproduce the issue yet but i'm really working on it. 
@Sephyr the thing is, the comments section is loaded in a ajaxy manner, after the page is rendered, 
so, as far as it goes, another rule is defined there https://github.com/nicu03/dark-youtube-theme/blob/master/chrome/manifest.json#L22 (so the styles for comments is in `dark_comments.css`)
Also, if you try to make any changes, make sure you always add the `!important` attribute, otherwise Chrome will ignore the custom style.
Please let me know if you manage to do anything

**Comment by nicu03** [comment]
@bauerp you said Safari, does my thing work on safari? :) or you meant chrome on ElCapitan?

**Comment by Sephyr** [comment]
@nicu03 so I tested a few things (which was easier then originally thought xD ) and managed to load an edited unpacked extension that i grabbed from Git, specifically the Chrome folder.

I then edited dark.css to include the following after line 316:
`.comment-renderer-text-content{
    color: #8d8d8d !important;
}`

This resulted in the comment text showing up as the specified color.
However, when I try to have that particular CSS bit to only be present in dark_comments.css it seems to have no effect at all and the comment text reverts back to black.

I dont have multiple browsers installed anymore so i can't say what effect this will have on Safari and Firefox, but Chrome seems to pick up on it without a hitch.

**Comment by bauerp** [comment]
Yes, the latest version of Safari. There was a Safari extension ("
dark-youtube-theme.safariextension
<https://github.com/nicu03/dark-youtube-theme/tree/master/dark-youtube-theme.safariextension>")
uploaded about 8 months ago (by you?) and it's been running perfect until
the comment issue that others are experiencing started.

2016-02-01 7:51 GMT-05:00 Nicu Natrapeiu <notifications@github.com>:

**Comment by nicu03** [comment]
@bauerp i wanted to publish it, but apple said i'm using youtube's name in
a misleading manner, so they denied my request. i guess somebody else
published it and i had no clue until now :))
i just found it on opera also ..
this is kind of weird :))

**Comment by nicu03** [comment]
@Sephyr great, i wish i could find a fix for it faster, but i tried on at least 10 machines with windows, osx and linux and I couldn't reproduce it.
I'll publish an update in a couple of minutes and i'll wait for some feedback 
If things go well, firefox will be next.
I'll let you know how this works.

**Thanks a lot!**

**Comment by nicu03** [comment]
@bauerp  can you please give me a link to the apple store, i cannot find it .
Thank you!

**Comment by bauerp** [comment]
It's actually not there. I downloaded it from here:
https://github.com/nicu03/dark-youtube-theme/tree/master/dark-youtube-theme.safariextension/build

2016-02-01 14:07 GMT-05:00 Nicu Natrapeiu <notifications@github.com>:

**Comment by nicu03** [comment]
@bauerp oh, got it, and you installed it from source .. that makes sense.
I'll try to talk again with the apple guys, maybe i'll make them understand that this **thing** is useful and there's no copyright infringements intended
I'll let you know how it goes.
Thanks!

**Comment by nicu03** [comment]
@mchladek if this fix works on chrome, i'll deploy it for firefox ASAP.
Thanks for your patience!

**Comment by Sephyr** [comment]
@nicu03 glad I could help :)

I have no idea what troubleshooting tools/methods you tried, but the way I found this one fairly easy is thanks to Chromes Developer Tools and the right-click Inspect feature it has on webpages.
Described bellow, may it prove useful to you in some way :)

Note: I am Chrome biased and havent used FF since Chrome came out. I recollect FF having a similar devtool, but i have no idea to what extend its features go.

I Inspected (right-click > Inspect) the black text from the comment (it will select and highlight the code in the Devtool) I made sure the proper element was being selected (hovering over the code highlights the elements in the browser) 
After i knew i had the right element (you can add new css in the Styles section and it will live-update the browser with the result)  I went through the Styles and Computed sections on the right and noticed that "color" was missing which had me check the css files which led me to my first post i made here :)

I've done a lot of CSS/HTML debugging and above method always proved useful to some extend :)

**Comment by nicu03** [comment]
@Sephyr the funny thing is that i know how to fix the issue (using inspect and chrome/ffox dev tools) **BUT** the problem is that on each and every machine i installed the latest version of the extension/addon, the comments section worked fine. That's what i meant when I said that "I cannot reproduce it"
Also, another weird thing is that the comments section broke around 20 January, and I didn't release a new version since December, which means YouTube updated their code base during this time (those nasty css classes and id-s) and that's why it crashed all of a sudden.
Thanks again
Version 2.2 is now released, please update it and let me know if it works.
Thanks again!

**Comment by Sephyr** [comment]
Installed 2.2 and after a CTRL+F5 its working like a charm!

**Comment by nicu03** [comment]
:+1:  great! 
Firefox will be next

**Comment by stolencard** [comment]
Thanks, the new update seemed to fix the issue. I just had to reinstall the extension for it to take effect.

**Comment by nicu03** [comment]
@stolencard it should have updated automatically, but doesn't matter .. IT WORKS!
The firefox update is also ready, but Mozilla changed the dev tools so i'll have to investigate a bit some stuff before publishing it, since there might be some dependency issues.
Thanks everyone!
